### ISSUE TITLE
We can't retrieve a rate 

### ISSUE THREAD

**Issue by ninjacoder30** [OxCom/magento-currency-services#5] opened 2019-07-01 10:14 UTC
I am getting error while importing using google.

We can't retrieve a rate from https://www.google.com/search?safe=off&q=10000+USD+AUD&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=100000+USD+BRL&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=100000+USD+CAD&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=100+USD+CNY&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=1000+USD+EUR&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=1000+USD+GBP&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=1000+USD+HKD&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=1000+USD+INR&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=100+USD+JPY&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=10000+USD+RUB&hl=en-EN.
We can't retrieve a rate from https://www.google.com/search?safe=off&q=10+USD+SGD&hl=en-EN.
Click "Save" to apply the rates we found.

**Comment by OxCom** [comment] 2019-07-04 14:14
I'm not able to reproduce. I will add logs for such cases, so we will be able to see why this happening.

**Comment by OxCom** [comment] 2020-07-07 19:30
should be fixed with latest release

**Closed as completed by OxCom** 2020-07-07 19:30 UTC
Labels: help wanted
